// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: pulse/v1/broker.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BrokerState mirrors the broker lifecycle state machine. Phase 1 exercises
// the full cycle; future phases (leader transfer, maintenance) extend it.
type BrokerState int32

const (
	BrokerState_BROKER_STATE_UNSPECIFIED BrokerState = 0
	BrokerState_BROKER_STATE_STARTING    BrokerState = 1
	BrokerState_BROKER_STATE_RECOVERING  BrokerState = 2
	BrokerState_BROKER_STATE_RUNNING     BrokerState = 3
	BrokerState_BROKER_STATE_DRAINING    BrokerState = 4
	BrokerState_BROKER_STATE_STOPPING    BrokerState = 5
	BrokerState_BROKER_STATE_STOPPED     BrokerState = 6
)

// Enum value maps for BrokerState.
var (
	BrokerState_name = map[int32]string{
		0: "BROKER_STATE_UNSPECIFIED",
		1: "BROKER_STATE_STARTING",
		2: "BROKER_STATE_RECOVERING",
		3: "BROKER_STATE_RUNNING",
		4: "BROKER_STATE_DRAINING",
		5: "BROKER_STATE_STOPPING",
		6: "BROKER_STATE_STOPPED",
	}
	BrokerState_value = map[string]int32{
		"BROKER_STATE_UNSPECIFIED": 0,
		"BROKER_STATE_STARTING":    1,
		"BROKER_STATE_RECOVERING":  2,
		"BROKER_STATE_RUNNING":     3,
		"BROKER_STATE_DRAINING":    4,
		"BROKER_STATE_STOPPING":    5,
		"BROKER_STATE_STOPPED":     6,
	}
)

func (x BrokerState) Enum() *BrokerState {
	p := new(BrokerState)
	*p = x
	return p
}

func (x BrokerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrokerState) Descriptor() protoreflect.EnumDescriptor {
	return file_pulse_v1_broker_proto_enumTypes[0].Descriptor()
}

func (BrokerState) Type() protoreflect.EnumType {
	return &file_pulse_v1_broker_proto_enumTypes[0]
}

func (x BrokerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrokerState.Descriptor instead.
func (BrokerState) EnumDescriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{0}
}

type BrokerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfoRequest) Reset() {
	*x = BrokerInfoRequest{}
	mi := &file_pulse_v1_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfoRequest) ProtoMessage() {}

func (x *BrokerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfoRequest.ProtoReflect.Descriptor instead.
func (*BrokerInfoRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{0}
}

// BrokerInfoResponse describes the local broker and its cluster identity.
type BrokerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id identifies the cluster this broker belongs to.
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// broker_id uniquely identifies this broker within the cluster.
	BrokerId string `protobuf:"bytes,2,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	// node_id uniquely identifies this physical node. It equals the broker_id
	// in single-node deployments and diverges once multiple brokers share a node.
	NodeId string `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// address is the advertised gRPC address clients should connect to.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// state is the current broker lifecycle state.
	State BrokerState `protobuf:"varint,5,opt,name=state,proto3,enum=pulse.v1.BrokerState" json:"state,omitempty"`
	// version is the Pulse release version.
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// started_at_ms is the wall-clock time the broker transitioned to Running.
	StartedAtMs int64 `protobuf:"varint,7,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	// topics is the number of topics currently registered.
	Topics        int32 `protobuf:"varint,8,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfoResponse) Reset() {
	*x = BrokerInfoResponse{}
	mi := &file_pulse_v1_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfoResponse) ProtoMessage() {}

func (x *BrokerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfoResponse.ProtoReflect.Descriptor instead.
func (*BrokerInfoResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{1}
}

func (x *BrokerInfoResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *BrokerInfoResponse) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *BrokerInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BrokerInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BrokerInfoResponse) GetState() BrokerState {
	if x != nil {
		return x.State
	}
	return BrokerState_BROKER_STATE_UNSPECIFIED
}

func (x *BrokerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BrokerInfoResponse) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *BrokerInfoResponse) GetTopics() int32 {
	if x != nil {
		return x.Topics
	}
	return 0
}

type CreateTopicRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config *TopicConfig           `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	// partitions must be 1 in Phase 1.
	Partitions    int32 `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_pulse_v1_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetConfig() *TopicConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateTopicRequest) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_pulse_v1_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_pulse_v1_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_pulse_v1_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{5}
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_pulse_v1_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{6}
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_pulse_v1_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_broker_proto_rawDescGZIP(), []int{7}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_pulse_v1_broker_proto protoreflect.FileDescriptor

const file_pulse_v1_broker_proto_rawDesc = "" +
	"\n" +
	"\x15pulse/v1/broker.proto\x12\bpulse.v1\x1a\x14pulse/v1/model.proto\"\x13\n" +
	"\x11BrokerInfoRequest\"\x86\x02\n" +
	"\x12BrokerInfoResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tbroker_id\x18\x02 \x01(\tR\bbrokerId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12+\n" +
	"\x05state\x18\x05 \x01(\x0e2\x15.pulse.v1.BrokerStateR\x05state\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\"\n" +
	"\rstarted_at_ms\x18\a \x01(\x03R\vstartedAtMs\x12\x16\n" +
	"\x06topics\x18\b \x01(\x05R\x06topics\"\x87\x01\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x15.pulse.v1.TopicConfigH\x00R\x06config\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\x05R\n" +
	"partitionsB\t\n" +
	"\a_config\"<\n" +
	"\x13CreateTopicResponse\x12%\n" +
	"\x05topic\x18\x01 \x01(\v2\x0f.pulse.v1.TopicR\x05topic\"(\n" +
	"\x12DeleteTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13DeleteTopicResponse\"\x13\n" +
	"\x11ListTopicsRequest\"=\n" +
	"\x12ListTopicsResponse\x12'\n" +
	"\x06topics\x18\x01 \x03(\v2\x0f.pulse.v1.TopicR\x06topics*\xcd\x01\n" +
	"\vBrokerState\x12\x1c\n" +
	"\x18BROKER_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BROKER_STATE_STARTING\x10\x01\x12\x1b\n" +
	"\x17BROKER_STATE_RECOVERING\x10\x02\x12\x18\n" +
	"\x14BROKER_STATE_RUNNING\x10\x03\x12\x19\n" +
	"\x15BROKER_STATE_DRAINING\x10\x04\x12\x19\n" +
	"\x15BROKER_STATE_STOPPING\x10\x05\x12\x18\n" +
	"\x14BROKER_STATE_STOPPED\x10\x062\xb2\x02\n" +
	"\x06Broker\x12J\n" +
	"\vCreateTopic\x12\x1c.pulse.v1.CreateTopicRequest\x1a\x1d.pulse.v1.CreateTopicResponse\x12J\n" +
	"\vDeleteTopic\x12\x1c.pulse.v1.DeleteTopicRequest\x1a\x1d.pulse.v1.DeleteTopicResponse\x12G\n" +
	"\n" +
	"ListTopics\x12\x1b.pulse.v1.ListTopicsRequest\x1a\x1c.pulse.v1.ListTopicsResponse\x12G\n" +
	"\n" +
	"BrokerInfo\x12\x1b.pulse.v1.BrokerInfoRequest\x1a\x1c.pulse.v1.BrokerInfoResponseB8Z6github.com/pulse-stream/pulse/pkg/api/pulse/v1/pulsepbb\x06proto3"

var (
	file_pulse_v1_broker_proto_rawDescOnce sync.Once
	file_pulse_v1_broker_proto_rawDescData []byte
)

func file_pulse_v1_broker_proto_rawDescGZIP() []byte {
	file_pulse_v1_broker_proto_rawDescOnce.Do(func() {
		file_pulse_v1_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulse_v1_broker_proto_rawDesc), len(file_pulse_v1_broker_proto_rawDesc)))
	})
	return file_pulse_v1_broker_proto_rawDescData
}

var file_pulse_v1_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pulse_v1_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pulse_v1_broker_proto_goTypes = []any{
	(BrokerState)(0),            // 0: pulse.v1.BrokerState
	(*BrokerInfoRequest)(nil),   // 1: pulse.v1.BrokerInfoRequest
	(*BrokerInfoResponse)(nil),  // 2: pulse.v1.BrokerInfoResponse
	(*CreateTopicRequest)(nil),  // 3: pulse.v1.CreateTopicRequest
	(*CreateTopicResponse)(nil), // 4: pulse.v1.CreateTopicResponse
	(*DeleteTopicRequest)(nil),  // 5: pulse.v1.DeleteTopicRequest
	(*DeleteTopicResponse)(nil), // 6: pulse.v1.DeleteTopicResponse
	(*ListTopicsRequest)(nil),   // 7: pulse.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),  // 8: pulse.v1.ListTopicsResponse
	(*TopicConfig)(nil),         // 9: pulse.v1.TopicConfig
	(*Topic)(nil),               // 10: pulse.v1.Topic
}
var file_pulse_v1_broker_proto_depIdxs = []int32{
	0,  // 0: pulse.v1.BrokerInfoResponse.state:type_name -> pulse.v1.BrokerState
	9,  // 1: pulse.v1.CreateTopicRequest.config:type_name -> pulse.v1.TopicConfig
	10, // 2: pulse.v1.CreateTopicResponse.topic:type_name -> pulse.v1.Topic
	10, // 3: pulse.v1.ListTopicsResponse.topics:type_name -> pulse.v1.Topic
	3,  // 4: pulse.v1.Broker.CreateTopic:input_type -> pulse.v1.CreateTopicRequest
	5,  // 5: pulse.v1.Broker.DeleteTopic:input_type -> pulse.v1.DeleteTopicRequest
	7,  // 6: pulse.v1.Broker.ListTopics:input_type -> pulse.v1.ListTopicsRequest
	1,  // 7: pulse.v1.Broker.BrokerInfo:input_type -> pulse.v1.BrokerInfoRequest
	4,  // 8: pulse.v1.Broker.CreateTopic:output_type -> pulse.v1.CreateTopicResponse
	6,  // 9: pulse.v1.Broker.DeleteTopic:output_type -> pulse.v1.DeleteTopicResponse
	8,  // 10: pulse.v1.Broker.ListTopics:output_type -> pulse.v1.ListTopicsResponse
	2,  // 11: pulse.v1.Broker.BrokerInfo:output_type -> pulse.v1.BrokerInfoResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pulse_v1_broker_proto_init() }
func file_pulse_v1_broker_proto_init() {
	if File_pulse_v1_broker_proto != nil {
		return
	}
	file_pulse_v1_model_proto_init()
	file_pulse_v1_broker_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulse_v1_broker_proto_rawDesc), len(file_pulse_v1_broker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulse_v1_broker_proto_goTypes,
		DependencyIndexes: file_pulse_v1_broker_proto_depIdxs,
		EnumInfos:         file_pulse_v1_broker_proto_enumTypes,
		MessageInfos:      file_pulse_v1_broker_proto_msgTypes,
	}.Build()
	File_pulse_v1_broker_proto = out.File
	file_pulse_v1_broker_proto_goTypes = nil
	file_pulse_v1_broker_proto_depIdxs = nil
}
