// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: pulse/v1/model.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic describes a named destination for event streams and its durable
// configuration. Phase 1 topics always have exactly one partition; the
// partition count field is present so that multi-partition topics can be
// enabled in a later phase without a wire-format change.
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    int32                  `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Config        *TopicConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,4,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_pulse_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_pulse_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *Topic) GetConfig() *TopicConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Topic) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// TopicConfig carries the durable retention and size limits applied to a
// topic. All limits are best-effort in Phase 1: they are persisted and served
// back through the API, while enforcement lands with the retention sweeper.
type TopicConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_message_bytes bounds the payload size of a single published message.
	MaxMessageBytes int64 `protobuf:"varint,1,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	// retention_ms is the maximum age of a message in milliseconds before it may
	// be deleted. Zero means no time-based retention.
	RetentionMs int64 `protobuf:"varint,2,opt,name=retention_ms,json=retentionMs,proto3" json:"retention_ms,omitempty"`
	// retention_bytes is the maximum size of a topic's log before the oldest
	// messages may be deleted. Zero means no size-based retention.
	RetentionBytes int64 `protobuf:"varint,3,opt,name=retention_bytes,json=retentionBytes,proto3" json:"retention_bytes,omitempty"`
	// cleanup_policy is "delete" (default) or "compact". Compaction is reserved
	// for a future phase.
	CleanupPolicy string `protobuf:"bytes,4,opt,name=cleanup_policy,json=cleanupPolicy,proto3" json:"cleanup_policy,omitempty"`
	// replication_factor is the number of replicas each partition should keep.
	// Phase 1 brokers are single-node and always use one.
	ReplicationFactor int32 `protobuf:"varint,5,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopicConfig) Reset() {
	*x = TopicConfig{}
	mi := &file_pulse_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicConfig) ProtoMessage() {}

func (x *TopicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicConfig.ProtoReflect.Descriptor instead.
func (*TopicConfig) Descriptor() ([]byte, []int) {
	return file_pulse_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *TopicConfig) GetMaxMessageBytes() int64 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

func (x *TopicConfig) GetRetentionMs() int64 {
	if x != nil {
		return x.RetentionMs
	}
	return 0
}

func (x *TopicConfig) GetRetentionBytes() int64 {
	if x != nil {
		return x.RetentionBytes
	}
	return 0
}

func (x *TopicConfig) GetCleanupPolicy() string {
	if x != nil {
		return x.CleanupPolicy
	}
	return ""
}

func (x *TopicConfig) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

// Message is the user-facing event model. All fields are advisory metadata
// except the payload; the broker enforces only structural validation.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is a ULID. Empty means the broker assigns one at publish time.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// key is an optional routing key used by future partitioning logic.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// payload is the opaque event body.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// headers is an unordered set of user-defined string attributes.
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// content_type describes the payload encoding, e.g. "application/json".
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// correlation_id links events that belong to the same logical operation.
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// trace_id carries distributed-tracing context through the broker.
	TraceId string `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// retry_count records how many times this event has been redelivered.
	RetryCount int32 `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// ttl_ms is the event time-to-live in milliseconds; zero means no TTL.
	TtlMs int64 `protobuf:"varint,9,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// priority orders messages within a partition. Lower is higher priority.
	Priority int32 `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	// schema_version identifies the payload schema; zero means unversioned.
	SchemaVersion int32 `protobuf:"varint,11,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pulse_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pulse_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Message) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Message) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// Record is a Message with its immutable log position and broker-assigned
// timestamp. Records are what consumers receive.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Message       *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pulse_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pulse_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *Record) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Record) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Record) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Record) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Record) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_pulse_v1_model_proto protoreflect.FileDescriptor

const file_pulse_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x14pulse/v1/model.proto\x12\bpulse.v1\"\x8e\x01\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\x05R\n" +
	"partitions\x12-\n" +
	"\x06config\x18\x03 \x01(\v2\x15.pulse.v1.TopicConfigR\x06config\x12\"\n" +
	"\rcreated_at_ms\x18\x04 \x01(\x03R\vcreatedAtMs\"\xdb\x01\n" +
	"\vTopicConfig\x12*\n" +
	"\x11max_message_bytes\x18\x01 \x01(\x03R\x0fmaxMessageBytes\x12!\n" +
	"\fretention_ms\x18\x02 \x01(\x03R\vretentionMs\x12'\n" +
	"\x0fretention_bytes\x18\x03 \x01(\x03R\x0eretentionBytes\x12%\n" +
	"\x0ecleanup_policy\x18\x04 \x01(\tR\rcleanupPolicy\x12-\n" +
	"\x12replication_factor\x18\x05 \x01(\x05R\x11replicationFactor\"\xa6\x03\n" +
	"\aMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\aheaders\x18\x04 \x03(\v2\x1e.pulse.v1.Message.HeadersEntryR\aheaders\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x15\n" +
	"\x06ttl_ms\x18\t \x01(\x03R\x05ttlMs\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12%\n" +
	"\x0eschema_version\x18\v \x01(\x05R\rschemaVersion\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x06Record\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12+\n" +
	"\amessage\x18\x05 \x01(\v2\x11.pulse.v1.MessageR\amessageB8Z6github.com/pulse-stream/pulse/pkg/api/pulse/v1/pulsepbb\x06proto3"

var (
	file_pulse_v1_model_proto_rawDescOnce sync.Once
	file_pulse_v1_model_proto_rawDescData []byte
)

func file_pulse_v1_model_proto_rawDescGZIP() []byte {
	file_pulse_v1_model_proto_rawDescOnce.Do(func() {
		file_pulse_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulse_v1_model_proto_rawDesc), len(file_pulse_v1_model_proto_rawDesc)))
	})
	return file_pulse_v1_model_proto_rawDescData
}

var file_pulse_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pulse_v1_model_proto_goTypes = []any{
	(*Topic)(nil),       // 0: pulse.v1.Topic
	(*TopicConfig)(nil), // 1: pulse.v1.TopicConfig
	(*Message)(nil),     // 2: pulse.v1.Message
	(*Record)(nil),      // 3: pulse.v1.Record
	nil,                 // 4: pulse.v1.Message.HeadersEntry
}
var file_pulse_v1_model_proto_depIdxs = []int32{
	1, // 0: pulse.v1.Topic.config:type_name -> pulse.v1.TopicConfig
	4, // 1: pulse.v1.Message.headers:type_name -> pulse.v1.Message.HeadersEntry
	2, // 2: pulse.v1.Record.message:type_name -> pulse.v1.Message
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pulse_v1_model_proto_init() }
func file_pulse_v1_model_proto_init() {
	if File_pulse_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulse_v1_model_proto_rawDesc), len(file_pulse_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulse_v1_model_proto_goTypes,
		DependencyIndexes: file_pulse_v1_model_proto_depIdxs,
		MessageInfos:      file_pulse_v1_model_proto_msgTypes,
	}.Build()
	File_pulse_v1_model_proto = out.File
	file_pulse_v1_model_proto_goTypes = nil
	file_pulse_v1_model_proto_depIdxs = nil
}
