// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: pulse/v1/pubsub.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Topic string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// partition must be 0 in Phase 1 (single-partition topics).
	Partition int32 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	// messages are appended as one batch and receive consecutive offsets.
	Messages      []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PublishRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PublishResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	// offsets is aligned with the request messages; each entry is the assigned
	// offset of the message at the same index.
	Offsets []int64 `protobuf:"varint,3,rep,packed,name=offsets,proto3" json:"offsets,omitempty"`
	// first_timestamp_ms is the broker-assigned timestamp of the batch.
	FirstTimestampMs int64 `protobuf:"varint,4,opt,name=first_timestamp_ms,json=firstTimestampMs,proto3" json:"first_timestamp_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PublishResponse) GetOffsets() []int64 {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *PublishResponse) GetFirstTimestampMs() int64 {
	if x != nil {
		return x.FirstTimestampMs
	}
	return 0
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consumer optionally names this consumer. When set and start_offset is
	// absent, the stream resumes from the consumer's last acknowledged offset.
	Consumer string `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// partition must be 0 in Phase 1.
	Partition int32 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	// start_offset optionally overrides any cursor. Absent means "resume from
	// the consumer's cursor (or 0)". When set, the value must be non-negative
	// and within the log bounds.
	StartOffset *int64 `protobuf:"varint,4,opt,name=start_offset,json=startOffset,proto3,oneof" json:"start_offset,omitempty"`
	// follow controls the end-of-log behavior. true streams new records as they
	// arrive; false replays to the current end of log and completes.
	Follow        bool `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *SubscribeRequest) GetStartOffset() int64 {
	if x != nil && x.StartOffset != nil {
		return *x.StartOffset
	}
	return 0
}

func (x *SubscribeRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// SubscribeResponse carries a batch of records. Records within one response
// are contiguous in offset.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consumer identifies the acknowledging consumer. Required.
	Consumer  string `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	// offset is the last offset successfully processed by the consumer. The
	// broker advances the consumer's stored cursor to this offset.
	Offset        int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *AckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *AckRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cursor is the stored cursor after the acknowledgment.
	Cursor        int64 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_pulse_v1_pubsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_v1_pubsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_pulse_v1_pubsub_proto_rawDescGZIP(), []int{5}
}

func (x *AckResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

var File_pulse_v1_pubsub_proto protoreflect.FileDescriptor

const file_pulse_v1_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x15pulse/v1/pubsub.proto\x12\bpulse.v1\x1a\x14pulse/v1/model.proto\"s\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12-\n" +
	"\bmessages\x18\x03 \x03(\v2\x11.pulse.v1.MessageR\bmessages\"\x8d\x01\n" +
	"\x0fPublishResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x18\n" +
	"\aoffsets\x18\x03 \x03(\x03R\aoffsets\x12,\n" +
	"\x12first_timestamp_ms\x18\x04 \x01(\x03R\x10firstTimestampMs\"\xb3\x01\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12&\n" +
	"\fstart_offset\x18\x04 \x01(\x03H\x00R\vstartOffset\x88\x01\x01\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06followB\x0f\n" +
	"\r_start_offset\"?\n" +
	"\x11SubscribeResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.pulse.v1.RecordR\arecords\"t\n" +
	"\n" +
	"AckRequest\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"%\n" +
	"\vAckResponse\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor2\xc4\x01\n" +
	"\x06PubSub\x12>\n" +
	"\aPublish\x12\x18.pulse.v1.PublishRequest\x1a\x19.pulse.v1.PublishResponse\x12F\n" +
	"\tSubscribe\x12\x1a.pulse.v1.SubscribeRequest\x1a\x1b.pulse.v1.SubscribeResponse0\x01\x122\n" +
	"\x03Ack\x12\x14.pulse.v1.AckRequest\x1a\x15.pulse.v1.AckResponseB8Z6github.com/pulse-stream/pulse/pkg/api/pulse/v1/pulsepbb\x06proto3"

var (
	file_pulse_v1_pubsub_proto_rawDescOnce sync.Once
	file_pulse_v1_pubsub_proto_rawDescData []byte
)

func file_pulse_v1_pubsub_proto_rawDescGZIP() []byte {
	file_pulse_v1_pubsub_proto_rawDescOnce.Do(func() {
		file_pulse_v1_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulse_v1_pubsub_proto_rawDesc), len(file_pulse_v1_pubsub_proto_rawDesc)))
	})
	return file_pulse_v1_pubsub_proto_rawDescData
}

var file_pulse_v1_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pulse_v1_pubsub_proto_goTypes = []any{
	(*PublishRequest)(nil),    // 0: pulse.v1.PublishRequest
	(*PublishResponse)(nil),   // 1: pulse.v1.PublishResponse
	(*SubscribeRequest)(nil),  // 2: pulse.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 3: pulse.v1.SubscribeResponse
	(*AckRequest)(nil),        // 4: pulse.v1.AckRequest
	(*AckResponse)(nil),       // 5: pulse.v1.AckResponse
	(*Message)(nil),           // 6: pulse.v1.Message
	(*Record)(nil),            // 7: pulse.v1.Record
}
var file_pulse_v1_pubsub_proto_depIdxs = []int32{
	6, // 0: pulse.v1.PublishRequest.messages:type_name -> pulse.v1.Message
	7, // 1: pulse.v1.SubscribeResponse.records:type_name -> pulse.v1.Record
	0, // 2: pulse.v1.PubSub.Publish:input_type -> pulse.v1.PublishRequest
	2, // 3: pulse.v1.PubSub.Subscribe:input_type -> pulse.v1.SubscribeRequest
	4, // 4: pulse.v1.PubSub.Ack:input_type -> pulse.v1.AckRequest
	1, // 5: pulse.v1.PubSub.Publish:output_type -> pulse.v1.PublishResponse
	3, // 6: pulse.v1.PubSub.Subscribe:output_type -> pulse.v1.SubscribeResponse
	5, // 7: pulse.v1.PubSub.Ack:output_type -> pulse.v1.AckResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pulse_v1_pubsub_proto_init() }
func file_pulse_v1_pubsub_proto_init() {
	if File_pulse_v1_pubsub_proto != nil {
		return
	}
	file_pulse_v1_model_proto_init()
	file_pulse_v1_pubsub_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulse_v1_pubsub_proto_rawDesc), len(file_pulse_v1_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulse_v1_pubsub_proto_goTypes,
		DependencyIndexes: file_pulse_v1_pubsub_proto_depIdxs,
		MessageInfos:      file_pulse_v1_pubsub_proto_msgTypes,
	}.Build()
	File_pulse_v1_pubsub_proto = out.File
	file_pulse_v1_pubsub_proto_goTypes = nil
	file_pulse_v1_pubsub_proto_depIdxs = nil
}
